apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: flask-app
  namespace: dev
spec:
  selector:
    matchLabels:
      app: flask-app
  replicas: 2
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: torres-template-flask:0.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: "FLASK_ENV"
          value: "development"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 20
          periodSeconds:
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 20
          periodSeconds: 5
        resources:
          limits:
            cpu: 300m
            memory: 1024Mi
          requests:
            cpu: 300m
            memory: 1024Mi

---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-svc
  namespace: dev
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: flask-app